FROM node:alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY yarn.lock yarn.lock
COPY package.json package.json

### AUTOGENERATED START
COPY apps/api/package.json apps/api/package.json
COPY apps/app/package.json apps/app/package.json
COPY apps/iframe/package.json apps/iframe/package.json
COPY apps/tester/package.json apps/tester/package.json
COPY packages/code-editor/package.json packages/code-editor/package.json
COPY packages/config/package.json packages/config/package.json
COPY packages/context-api/package.json packages/context-api/package.json
COPY packages/contract/package.json packages/contract/package.json
COPY packages/mongodb2/package.json packages/mongodb2/package.json
COPY packages/pd-cli/package.json packages/pd-cli/package.json
COPY packages/schema/package.json packages/schema/package.json
COPY packages/shared/package.json packages/shared/package.json
COPY packages-pvd/schema/package.json packages-pvd/schema/package.json
COPY packages-pvd/tester/package.json packages-pvd/tester/package.json
COPY packages-pvd/tools/package.json packages-pvd/tools/package.json
COPY packages-pvd/types/package.json packages-pvd/types/package.json
COPY packages-pvd/ui/package.json packages-pvd/ui/package.json
### AUTOGENERATED END

RUN yarn install
ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001
USER nextjs

COPY . .

EXPOSE 3001
